### ISSUE TITLE
3llo crashes on some invalid commands

### ISSUE THREAD

**Issue by f-breidenstein** [qcam/3llo#24]
**What I did**
Entered `list` or `board` in the 3llo commandline

**What  I expected**
An `Invalid command` warning (Which gets printed when you e.g. just enter `card` without any arugments)

**What happend instead**
The programm crashes with a NoMethodError.
```
 3llo  > board
Traceback (most recent call last):
	7: from /home/fleaz/.gem/ruby/2.5.0/bin/3llo:23:in `<main>'
	6: from /home/fleaz/.gem/ruby/2.5.0/bin/3llo:23:in `load'
	5: from /home/fleaz/.gem/ruby/2.5.0/gems/3llo-0.1.11/bin/3llo:31:in `<top (required)>'
	4: from /home/fleaz/.gem/ruby/2.5.0/gems/3llo-0.1.11/lib/3llo/controller.rb:14:in `start'
	3: from /home/fleaz/.gem/ruby/2.5.0/gems/3llo-0.1.11/lib/3llo/controller.rb:14:in `loop'
	2: from /home/fleaz/.gem/ruby/2.5.0/gems/3llo-0.1.11/lib/3llo/controller.rb:20:in `block in start'
	1: from /home/fleaz/.gem/ruby/2.5.0/gems/3llo-0.1.11/lib/3llo/command_factory.rb:20:in `factory'
/home/fleaz/.gem/ruby/2.5.0/gems/3llo-0.1.11/lib/3llo/board_command_factory.rb:13:in `factory': undefined method `to_sym' for nil:NilClass (NoMethodError)
```

Best regards,
Felix

**Comment by qcam** [comment]
@f-breidenstein Perfect bug report 👍, will fix it some time next week.

**Comment by qcam** [comment]
This should be fixed via #25 in `v0.1.12`, give it a try! ❤️

**Comment by qcam** [comment]
@davealbert Thanks for the report, could you specify the steps to reproduce that? I will give it a look.

**Comment by davealbert** [comment]
@qcam 

* open 3llo
* `board list` -- Works fine shows list of boards as expected.
* `board select` with any or without additional arguments.
* crash:

```
/Library/Ruby/Gems/2.0.0/gems/3llo-0.1.12/lib/3llo/commands/board/select.rb:25:in `board_choices': undefined method `to_h' for #<Array:0x007fc7af9eb578> (NoMethodError)
        from /Library/Ruby/Gems/2.0.0/gems/3llo-0.1.12/lib/3llo/commands/board/select.rb:17:in `select_board'
        from /Library/Ruby/Gems/2.0.0/gems/3llo-0.1.12/lib/3llo/commands/board/select.rb:6:in `execute'
        from /Library/Ruby/Gems/2.0.0/gems/3llo-0.1.12/lib/3llo/controller.rb:20:in `block in start'
        from /Library/Ruby/Gems/2.0.0/gems/3llo-0.1.12/lib/3llo/controller.rb:14:in `loop'
        from /Library/Ruby/Gems/2.0.0/gems/3llo-0.1.12/lib/3llo/controller.rb:14:in `start'
        from /Library/Ruby/Gems/2.0.0/gems/3llo-0.1.12/bin/3llo:31:in `<top (required)>'
        from /usr/local/bin/3llo:23:in `load'
        from /usr/local/bin/3llo:23:in `<main>'
```


Thanks

**Comment by davealbert** [comment]
@qcam Could it be my version of ruby?  I'm just using the mac system version ... I think.

`$ ruby -v`
`ruby 2.0.0p648 (2015-12-16 revision 53162) [universal.x86_64-darwin16]`
