### ISSUE TITLE
Traceback when exiting with Ctrl-D

### ISSUE THREAD

**Issue by voidcase** [qcam/3llo#40]
```
 3llo  > Traceback (most recent call last):
	6: from /home/isak/.gem/ruby/2.5.0/bin/3llo:23:in `<main>'
	5: from /home/isak/.gem/ruby/2.5.0/bin/3llo:23:in `load'
	4: from /home/isak/.gem/ruby/2.5.0/gems/3llo-0.3.1/bin/3llo:45:in `<top (required)>'
	3: from /home/isak/.gem/ruby/2.5.0/gems/3llo-0.3.1/lib/3llo/controller.rb:14:in `start'
	2: from /home/isak/.gem/ruby/2.5.0/gems/3llo-0.3.1/lib/3llo/controller.rb:14:in `loop'
	1: from /home/isak/.gem/ruby/2.5.0/gems/3llo-0.3.1/lib/3llo/controller.rb:20:in `block in start'
/home/isak/.gem/ruby/2.5.0/gems/3llo-0.3.1/lib/3llo/command_factory.rb:16:in `factory': undefined method `strip' for nil:NilClass (NoMethodError)
```

**Comment by qcam** [comment]
@voidcase thanks for the report. Unfortunately I could not find time to submit a patch. Would you mind sending a PR? It should be a quick fix I suppose.
